### ISSUE TITLE
Outfitter

### ISSUE THREAD

**Issue by Lee-Townage** [Adde-Endless-Sky/AES-Aben#1]
The Aben do not have an outfitter on either of their planets. I installed the plugin about a week ago, and updated today, still no outfitter?

**Comment by Darcman99** [comment]
The Aben only open their outfitter to the player after they have completed a number of tasks, there are two tiers of outfitter unlocks.

**Comment by Lee-Townage** [comment]
Yes, I have given them all the tech items they are interested in and I have did the scout mission, and they said I may buy their stuff, but I dont see where

**Comment by Lee-Townage** [comment]
I see this in Errors.txt

An expression must either perform a comparison, or an assign a value:
file "C:/Users/Jarrod/AppData/Roaming/endless-sky/plugins/AES-Aben-master/data/tech unlock.txt"
L5:   mission "aben unlock basic"
L13:     on offer
L14:       set 'license: Aben Technology'
(Bactrian):
outfit space: -28
weapon capacity: -28
	1 Hyperdrive
	19 Mass Expansion
	1 Supercapacitor
	2 Heavy Anti-Missile Turret
	3 Liquid Helium Cooler
	1 Afterburner
	1 A250 Atomic Thruster
	1 A375 Atomic Steering
	1 A865 Atomic Steering
	3 Quad Blaster Turret
	2 Fusion Reactor
	1 LP144a Battery Pack
	4 S-970 Regenerator
	1 Catalytic Ramscoop
	1 Plasma Turret
	2 Mass Driver
	200 Inertia Buffered Slug
	1 Rapid Fire Plasma Weapon
	1 Hyper Ionized Plasma Cannon

(Bactrian):
outfit space: -28
weapon capacity: -28
	1 Hyperdrive
	19 Mass Expansion
	1 Supercapacitor
	2 Heavy Anti-Missile Turret
	3 Liquid Helium Cooler
	1 Afterburner
	1 A250 Atomic Thruster
	1 A375 Atomic Steering
	1 A865 Atomic Steering
	3 Quad Blaster Turret
	2 Fusion Reactor
	1 LP144a Battery Pack
	4 S-970 Regenerator
	1 Catalytic Ramscoop
	1 Plasma Turret
	2 Mass Driver
	200 Inertia Buffered Slug
	1 Rapid Fire Plasma Weapon
	1 Hyper Ionized Plasma Cannon

(Corvette):
outfit space: -41
	1 Hyperdrive
	2 Mass Expansion
	2 Liquid Helium Cooler
	1 A370 Atomic Thruster
	1 A375 Atomic Steering
	1 White Sun Reactor
	1 S-970 Regenerator
	1 Catalytic Ramscoop
	4 Ion Beam
	2 Ion Beam Turret

(Kestrel):
engine capacity: -9
	1 Hyperdrive
	6 Mass Expansion
	3 Korath Heat Shunt
	3 Supercapacitor
	1 LP072a Battery Pack
	1 A860 Atomic Thruster
	1 A865 Atomic Steering
	2 Fusion Reactor
	1 LP036a Battery Pack
	1 S-970 Regenerator
	1 Catalytic Ramscoop
	2 Korath Warder
	2 Rapid Fire Plasma Weapon
	4 Hyper Ionized Plasma Cannon

(Kestrel):
engine capacity: -9
	1 Hyperdrive
	6 Mass Expansion
	3 Korath Heat Shunt
	1 A860 Atomic Thruster
	1 A865 Atomic Steering
	1 White Sun Reactor
	1 Fusion Reactor
	1 LP036a Battery Pack
	1 S-970 Regenerator
	1 Catalytic Ramscoop
	2 Korath Warder
	2 Rapid Fire Plasma Weapon
	4 Hyper Ionized Plasma Cannon

(Osprey):
outfit space: -26
	1 Hyperdrive
	2 Mass Expansion
	1 Korath Heat Shunt
	3 Supercapacitor
	1 LP072a Battery Pack
	1 A370 Atomic Thruster
	1 A525 Atomic Steering
	1 Fusion Reactor
	1 Liquid Nitrogen Cooler
	1 S-970 Regenerator
	1 Korath Warder
	2 Mass Driver
	2 Rapid Fire Plasma Weapon

(Osprey):
outfit space: -27
	1 Hyperdrive
	2 Mass Expansion
	1 Korath Heat Shunt
	1 A370 Atomic Thruster
	1 A525 Atomic Steering
	1 White Sun Reactor
	1 Liquid Nitrogen Cooler
	1 S-970 Regenerator
	1 Korath Warder
	2 Mass Driver
	2 Rapid Fire Plasma Weapon

Vitreus: outfit "Fractal Beam" equipped but not included in outfit list.
(Vitreus):
outfit space: -119
	1 Jump Drive
	1 Adamas Amethyst Steering
	2 A.S.R. Mk III
	1 Adamas Amethyst Thruster
	1 Adamas Onyx Core
	10 Interior Autoturret
	1 Massive Heat Disperser
	2 Adamas Aerugite Thruster
	4 Needler
	1600 Needle Shard

Warning: outfitter "aben advanced" is referred to, but has no outfits.
Warning: outfitter "aben basic" is referred to, but has no outfits.
Warning: planet "Biotite Station" is referred to, but never defined.
Warning: planet "Reminder Vortex" is referred to, but never defined.

**Comment by Darcman99** [comment]
I have pushed a patch to fix the issue. Download it [here](https://github.com/Adde-Endless-Sky/AES-Aben/archive/master.zip). Please confirm if this has helped the issue.

**Comment by Lee-Townage** [comment]
Still no outfitter button on either planet, errors.txt still has
An expression must either perform a comparison, or an assign a value:
file "C:/Users/Jarrod/AppData/Roaming/endless-sky/plugins/AES-Aben-master/data/tech unlock.txt"
L5: mission "aben unlock basic"
L13: on offer
L14: set 'license: Aben Technology'

and

Warning: outfitter "aben advanced" is referred to, but has no outfits.
Warning: outfitter "aben basic" is referred to, but has no outfits.

**Comment by Lee-Townage** [comment]
maybe because I did that mission to give me the license while I still had the old version?

**Comment by Darcman99** [comment]
I have tested on the most recent Aben download and I can confirm it is working as intended. Are you sure you have completed Recon and supplied them with 2 sets of outfits? Additionally you would need to depart the planet and return for the planet to update with the outfitters.

**Comment by Lee-Townage** [comment]
I actually looked at the retrieval text to see exactly what they wanted, and made sure I brought them two of the largest of every different thing they wanted, and then I think clicked spaceport and got the scout mission, did that real quick, they thanked me, assured me I could access their tech, and there was still no outfitter button. and thats when I decided to look for an update, installed it, tried again, still nothing, then I opened this. And I also downloaded the patch you linked and updated a second time. I am running endless sky 0.9.12 through steam, could that be the issue?

**Comment by Darcman99** [comment]
Aben is developed on nightly, there could well be issues with compatibility but I doubt that would be the problem here. Also that patch seems to have lagged behind, I only got the notification for the update just now so you may need to reinstalled the plugin.

**Comment by Lee-Townage** [comment]
That worked perfectly! Thanks!
