### ISSUE TITLE
Hi there! Do you know if your mods are compatible with all of these other mods?

### ISSUE THREAD

**Issue by endlessskymodfan13** [Adde-Endless-Sky/AES-Aben#2]
I am using continuous, I hope to use in combination all of the Adde mods, HighDPI, and everything linked below. Will I probably be okay? Shields up does seem to add some places on the edges of the galaxy, but I think Adde does too. Will these just overlap harmlessly enough to ignore it? Thank you for reading my question, Please have a nice day.

https://github.com/Adde-Endless-Sky
https://github.com/endless-sky/endless-sky-high-dpi

https://github.com/geojak/Czartrak-s-Ship-Pack
https://github.com/beccabunny/Beccas-Endless-Expansion/releases/tag/1.2.0
https://github.com/beccabunny/ES-Restock/releases/tag/v3.1
https://github.com/toilethinges/Adamas-Project
https://github.com/Amazinite/Shields-Up/releases/tag/V1.1

**Comment by endlessskymodfan13** [comment]
I just wanted to clarify, if the systems overlap each other and it looks weird, I can ignore that and it wont bother me too much. I'm just worried it breaks something.

**Comment by Darcman99** [comment]
I am confident that all Adde plugins are compatible with most other plugins out there. I will test compatibility with the plugins you listed when I have time to, just to be sure.

**Comment by endlessskymodfan13** [comment]
Wow thank you I really appreciate that! I just want to be clear that I would never bother you with such a thing if I knew how to test it myself. I tried to add them and I don't really notice anything different, so it would likely be a very prolonged mystery for me until I suddenly discover a game breaking problem, multiple hours or days into gameplay...

Honestly when I asked if you knew if they were compatible, I never expected you to tell me you would test them. I really appreciate that a lot. I hope it's not a really difficult and frustrating thing to do. God bless.

**Comment by endlessskymodfan13** [comment]
Hey, I may not be great at making mods, but I made a thread inside of which you receive a big shout out for the whole community :D
https://nm.reddit.com/r/endlesssky/comments/iynztf/what_are_the_best_currently_functioning_endless/

**Comment by endlessskymodfan13** [comment]
Hey there, maybe this is just my paranoia, but I am just saying I'm still here. No rush or pressure, I just worry because it's closed, even though I know you said in the other issue that closed doesn't mean, like closed closed.
I'm only just saying, I am here, and I have not uhhh, like uhh, you know, gone away lol. Just saying. Not saying anything else in any way. :)

**Comment by Darcman99** [comment]
All those mods should be compatible with each other, good to go. If you are ever worried about compatibility you can test by starting a new pilot and explore the map for any conflicts using the developer ship provided by Omnis.

**Comment by endlessskymodfan13** [comment]
Thank you so much! (I didn't know about the developer ship, but now I will look for it!)
I am so happy about this! You have really saved me from a great deal of confusion! God bless!
